const ImgActionTypes = {
  UPLOAD_START: "UPLOAD_START",
  UPLOAD_FINISHED: "UPLOAD_FINISHED",
  UPLOAD_FAILED: "UPLOAD_FAILED",
  DELETE_IMAGE: "DELETE_IMAGE",
  DELETE_FAILED: "DELETE_FAILED",
  DELETE_FINISHED: "DELETE_FINISHED",
  LOAD_IMG: "LOAD_IMG",
  UPDATE_URL: "UPDATE_URL"
};
export default ImgActionTypes;
