const AdminFormActionTypes = {
  SUBMIT_ADMIN_START: "SUBMIT_ADMIN_START",
  SUBMIT_SUCCESS: "SUBMIT_SUCCESS",
  SUBMIT_FAIL: "SUBMIT_FAIL",
  ISEXISTING: "ISEXISTING",
  CLOSEMODAL: "CLOSEMODAL",
  SUBMIT_EXISTING_START: "SUBMIT_EXISTING_START"
  // SUBMIT_EXISTING_SUCCESS: "SUBMIT_SUCCESS",
  // SUBMIT_EXISTING_FAIL: "SUBMIT_FAIL"
};

export default AdminFormActionTypes;
