const RetriveActionTypes = {
  VALIDATE_CRED_START: "VALIDATE_CRED_START",
  VALIDATE_CRED_FINISHED: "VALIDATE_CRED_START",
  VALIDATE_CRED_FAILED: "VALIDATE_CRED_FAILED",

  UPDATE_CRED_START: "UPDATE_CRED_START",
  UPDATE_CRED_FINISHED: "UPDATE_CRED_FINISHED",
  UPDATE_CRED_FAILED: "UPDATE_CRED_FAILED"
};

export default RetriveActionTypes;
